Repository Learning-Is-Vital-In-Development/24-sql-tuning, pull requests merged in 2024-05, with the labels that each got.

#27 5주차 - 인덱스 튜닝 Part 2 정리
  study/week_05/심대수.md
Labels: size/XS

#26 [5주차] 이세희 3장 정리
  study/week_04/이세희.md
  study/week_05/이세희.md
Labels: size/XS

#24 5회차 내용 정리
  study/week_05/한예성.md
  study/week_05/한예성/image-1.png
  study/week_05/한예성/image-10.png
  study/week_05/한예성/image-11.png
  study/week_05/한예성/image-12.png
  study/week_05/한예성/image-13.png
  study/week_05/한예성/image-14.png
  study/week_05/한예성/image-2.png
  study/week_05/한예성/image-3.png
  study/week_05/한예성/image-4.png
  study/week_05/한예성/image-5.png
  study/week_05/한예성/image-6.png
  study/week_05/한예성/image-7.png
  study/week_05/한예성/image-8.png
  study/week_05/한예성/image-9.png
  study/week_05/한예성/image.png
  study/week_05/한예성/한예성.md
Labels: size/L

#23 [5주차] 남은찬 3장 정리
  study/week_05/남은찬.md
Labels: size/XS

#22 [5주차] 홍성주 3장 정리
  study/week_04/홍성주/홍성주.md
  study/week_05/홍성주/홍성주.md
Labels: size/L

#25 [5주차] 김범석 3장 정리
  study/week_05/김범석.md
Labels: size/XS

#35 [이세희] 6주차 스터디 내용 정리
  study/week_06/이세희.md
Labels: size/XS

#33 6주차 - 조인 튜닝 Part 1 정리
  study/week_06/심대수.md
Labels: size/XS

#32 6주차 내용 정리
  study/week_06/한예성.md
  study/week_06/한예성/image-1.png
  study/week_06/한예성/image-2.png
  study/week_06/한예성/image-3.png
  study/week_06/한예성/image-4.png
  study/week_06/한예성/image.png
  study/week_06/한예성/한예성.md
Labels: size/M

#31 6주차 정리 남은찬
  study/week_06/남은찬.md
Labels: size/XS

#30 [6주차] 홍성주 4장 조인
  study/week_06/홍성주/image/NLjoin.jpg
  study/week_06/홍성주/image/innerloopjoinfullscan.jpg
  study/week_06/홍성주/홍성주.md
Labels: size/L

#28 5주차 스터디 내용 추가.
  study/week_05/한종상/images/Untitled.png
  study/week_05/한종상/images/Untitled1.png
  study/week_05/한종상/images/Untitled10.png
  study/week_05/한종상/images/Untitled11.png
  study/week_05/한종상/images/Untitled12.png
  study/week_05/한종상/images/Untitled13.png
  study/week_05/한종상/images/Untitled14.png
  study/week_05/한종상/images/Untitled15.png
  study/week_05/한종상/images/Untitled16.png
  study/week_05/한종상/images/Untitled17.png
  study/week_05/한종상/images/Untitled18.png
  study/week_05/한종상/images/Untitled19.png
  study/week_05/한종상/images/Untitled2.png
  study/week_05/한종상/images/Untitled20.png
  study/week_05/한종상/images/Untitled21.png
  study/week_05/한종상/images/Untitled22.png
  study/week_05/한종상/images/Untitled23.png
  study/week_05/한종상/images/Untitled24.png
  study/week_05/한종상/images/Untitled25.png
  study/week_05/한종상/images/Untitled26.png
  study/week_05/한종상/images/Untitled27.png
  study/week_05/한종상/images/Untitled3.png
  study/week_05/한종상/images/Untitled4.png
  study/week_05/한종상/images/Untitled5.png
  study/week_05/한종상/images/Untitled6.png
  study/week_05/한종상/images/Untitled7.png
  study/week_05/한종상/images/Untitled8.png
  study/week_05/한종상/images/Untitled9.png
  study/week_05/한종상/한종상.md
Labels: size/XL

#34 6주차 - 조인 튜닝
  study/week_06/김범석.md
Labels: size/XS

#39 7주차 내용 정리
  study/week_06/한예성/한예성.md
  study/week_07/한예성/image-1.png
  study/week_07/한예성/image-2.png
  study/week_07/한예성/image-3.png
  study/week_07/한예성/image.png
  study/week_07/한예성/한예성.md
Labels: size/XS

#38 [7주차] 남은찬 4장
  study/week_07/남은찬.md
Labels: size/XS

#37 [7주차] 홍성주 4장
  study/week_07/홍성주/image/join.jpg
  study/week_07/홍성주/홍성주.md
Labels: size/L

#36 6주차 NL, 소트머지 조인 정리
  study/week_06/한종상/images/Untitled.png
  study/week_06/한종상/images/Untitled1.png
  study/week_06/한종상/images/Untitled10.png
  study/week_06/한종상/images/Untitled2.png
  study/week_06/한종상/images/Untitled3.png
  study/week_06/한종상/images/Untitled4.png
  study/week_06/한종상/images/Untitled5.png
  study/week_06/한종상/images/Untitled6.png
  study/week_06/한종상/images/Untitled7.png
  study/week_06/한종상/images/Untitled8.png
  study/week_06/한종상/images/Untitled9.png
  study/week_06/한종상/한종상.md
Labels: size/L

#40 [한종상] 7주차 스터디 내용 추가.
  study/week_07/한종상/images/Untitled.png
  study/week_07/한종상/images/Untitled1.png
  study/week_07/한종상/images/Untitled2.png
  study/week_07/한종상/images/Untitled3.png
  study/week_07/한종상/images/Untitled4.png
  study/week_07/한종상/images/Untitled5.png
  study/week_07/한종상/한종상.md
Labels: size/L
