Repository Learning-Is-Vital-In-Development/24-sql-tuning, pull requests merged in 2024-04, with the labels that each got.

#1 add: 초기 스터디 파일 세팅
  README.md
  study/week_01/한예성.md
  study/week_02/한예성.md
  study/week_03/한예성.md
  study/week_04/한예성.md
  study/week_05/한예성.md
  study/week_06/한예성.md
  study/week_07/한예성.md
  study/week_08/한예성.md
  study/week_09/한예성.md
  study/week_10/한예성.md
  study/week_11/한예성.md
  study/week_12/한예성.md
Labels: size/L

#5 1장 요약 및 정리
  study/week_02/김범석/images/image-1.png
  study/week_02/김범석/images/image-2.png
  study/week_02/김범석/images/image-3.png
  study/week_02/김범석/images/image-4.png
  study/week_02/김범석/images/image-5.png
  study/week_02/김범석/김범석.md
Labels: size/L

#3 [1장] 홍성주
  study/week_02/홍성주/db storage structure.png
  study/week_02/홍성주/process 생명주기.png
  study/week_02/홍성주/sga.jpg
  study/week_02/홍성주/버퍼캐시.jpg
  study/week_02/홍성주/익스텐트.png
  study/week_02/홍성주/홍성주.md
Labels: size/L

#8 fix: pr_auto_merge.yaml 수정
  .github/workflows/pr_auto_merge.yaml
Labels: size/XS

#4 [1장] 이세희
  study/week_02/이세희.md
Labels: size/XS

#6 [1장] 남은찬
  study/week_01/남은찬.md
  study/week_02/남은찬.md
Labels: size/L

#10 2장 정리 내용 추가
  study/week_02/한예성.md
  study/week_02/한예성/1장 정리.md
  study/week_03/한예성.md
  study/week_03/한예성/2024-04-20-05-49-26.png
  study/week_03/한예성/2024-04-20-05-49-47.png
  study/week_03/한예성/2024-04-20-05-50-15.png
  study/week_03/한예성/2024-04-20-05-50-52.png
  study/week_03/한예성/2024-04-20-05-51-09.png
  study/week_03/한예성/2024-04-20-05-51-54.png
  study/week_03/한예성/2024-04-20-05-52-49.png
  study/week_03/한예성/2024-04-20-05-53-07.png
  study/week_03/한예성/2024-04-20-05-53-52.png
  study/week_03/한예성/2024-04-20-05-54-30.png
  study/week_03/한예성/2장_1.md
  study/week_03/한예성/2장_2.md
  study/week_03/한예성/image.png
Labels: size/XL

#9 docs: 1-2주차 스터디 내용 추가.
  study/week_02/한종상/images/img1.png
  study/week_02/한종상/images/img2.png
  study/week_02/한종상/images/img3.png
  study/week_02/한종상/images/img4.png
  study/week_02/한종상/images/img5.png
  study/week_02/한종상/images/img6.png
  study/week_02/한종상/images/img7.png
  study/week_02/한종상/images/img8.png
  study/week_02/한종상/한종상.md
  study/week_03/한종상/images/Untitled.png
  study/week_03/한종상/images/Untitled1.png
  study/week_03/한종상/images/Untitled2.png
  study/week_03/한종상/images/Untitled3.png
  study/week_03/한종상/images/Untitled4.png
  study/week_03/한종상/images/Untitled5.png
  study/week_03/한종상/images/Untitled6.png
  study/week_03/한종상/images/Untitled7.png
  study/week_03/한종상/한종상.md
Labels: size/XL

#13 1주차, 2주차 정리 추가
  study/week_01/심대수.md
  study/week_02/심대수.md
Labels: size/XS

#12 [1장, 2장] 2주차 3주차 정리 김강훈
  study/week_02/김강훈.md
  study/week_03/김강훈.md
Labels: size/L

#11 [2장] 홍성주 인덱스 기본
  study/week_03/홍성주/image/indexRangeScan.jpg
  study/week_03/홍성주/image/indexSkipScan.png
  study/week_03/홍성주/image/index_b_tree.png
  study/week_03/홍성주/image/logicalIndexTree.jpg
  study/week_03/홍성주/image/physicalIndexTree.jpg
  study/week_03/홍성주/홍성주.md
Labels: size/L

#18 4주차 스터티 내용 추가.
  study/week_04/한종상/images/Untitled.png
  study/week_04/한종상/images/Untitled1.png
  study/week_04/한종상/images/Untitled2.png
  study/week_04/한종상/images/Untitled3.png
  study/week_04/한종상/images/Untitled4.png
  study/week_04/한종상/images/Untitled5.png
  study/week_04/한종상/images/Untitled6.png
  study/week_04/한종상/한종상.md
Labels: size/L

#21 4회차 내용 정리
  study/week_04/한예성.md
  study/week_04/한예성/image-1.png
  study/week_04/한예성/image-2.png
  study/week_04/한예성/image.png
  study/week_04/한예성/한예성.md
Labels: size/L

#20 4주차 - 인덱스 튜닝 Part 1 정리
  study/week_04/심대수.md
Labels: size/XS

#16 [남은찬] 2장 요약 정리
  study/week_01/남은찬.md
  study/week_03/남은찬.md
Labels: size/L

#15 [김범석] 2장 요약 정리
  study/week_03/김범석.md
  study/week_04/김범석.md
Labels: size/XS

#14 [이세희] 2장 요약 정리
  study/week_03/이세희.md
Labels: size/XS
